"""
Keep SIGPIPE blocked, so a write to a vanished peer raises instead of killing.

libsane puts SIGPIPE back to its default action, at the C level, after a scan
read that ends with an error status -- and the end of every feeder batch is
such a read.  It does so behind Python's back: ``signal.getsignal`` still
reports ``SIG_IGN``.  From then on a write to a socket or pipe whose peer has
gone, such as a paperless upload or a web client that hung up, would end the
whole process silently.

Blocking the signal makes its disposition irrelevant.  A blocked SIGPIPE that
a write generates stays pending instead of being delivered, and the write
fails with EPIPE, which Python raises as ``BrokenPipeError``.

The blocked mask belongs to a thread and is copied to every thread it starts,
so it is set once in the main thread, before any other thread exists.  The
mask also survives fork and exec, so a program saneless launches would start
with SIGPIPE blocked.  The standard library's ``subprocess`` resets the
signal's *disposition* in the child (``restore_signals``), but not the mask,
and has no parameter for it; a launch is therefore wrapped in
``sigpipe_unblocked``.
"""

from __future__ import annotations

import contextlib
import signal
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Generator

__all__ = ["block_sigpipe", "sigpipe_unblocked"]


def block_sigpipe() -> None:
    """
    Add SIGPIPE to the calling thread's blocked mask.

    Called from the main thread before any other thread starts, so every
    thread started afterwards inherits the mask.
    """
    signal.pthread_sigmask(signal.SIG_BLOCK, {signal.SIGPIPE})


@contextlib.contextmanager
def sigpipe_unblocked() -> Generator[None]:
    """
    Unblock SIGPIPE in the calling thread for the body, then restore the mask.

    Meant for the launch of a child program, which inherits the mask of the
    thread that starts it and must not start with SIGPIPE blocked.

    A SIGPIPE already pending in this thread, left by an earlier write that
    failed with EPIPE, is discarded first: it would be delivered the moment
    the signal is unblocked, under the default action libsane may have put
    back, and kill the process.

    Only the calling thread is affected: a SIGPIPE generated by a write in
    another thread is directed at that thread and stays blocked there.  The
    body should do no writes of its own to a pipe or socket whose peer can
    close; launching a process does none in the parent.

    Yields:
        None, while SIGPIPE is unblocked in the calling thread.

    """
    previous = signal.pthread_sigmask(signal.SIG_BLOCK, set())
    try:
        if signal.SIGPIPE in previous:
            while signal.sigtimedwait({signal.SIGPIPE}, 0) is not None:
                pass
            signal.pthread_sigmask(signal.SIG_UNBLOCK, {signal.SIGPIPE})
        yield
    finally:
        signal.pthread_sigmask(signal.SIG_SETMASK, previous)
